version: '3.8'

services:

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${redis.pw}"]
    environment:
      - network.host=${net.ip}
    restart: unless-stopped
    networks:
      - elastic_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node # 싱글노드 사용
      - ELASTIC_PASSWORD=${elastic.pw}
      - xpack.security.enabled=true   # 보안 활성화
      - network.host=${net.ip}
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - elastic_network

volumes:
  esdata:
    driver: local

networks:
  elastic_network:
    driver: bridge
