    # PillTip\BE\src\main\resources\application.yml
    # author : mireutale
    # date : 2025-05-19
    # description : spring security, google, kakao 설정

    config:
      import: optional:file:.env[.properties]

    spring:
      datasource:
        # JDBC 드라이버 - Mysql / Mysql 서버 주소 / 데이터베이스 이름 / 사용SSL / 시간대 / 공개키 복구 허용
        # SSL이 없으면 클라이언트가 서버로부터 공개 키를 가져와야 암호화된 로그인 처리가 가능(http 프로토콜 사용시)
        url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true # 데이터베이스 연결 정보
        username: ${DB_USER} # 데이터베이스 사용자 이름
        password: ${DB_PASSWORD} # 데이터베이스 사용자 비밀번호
        driver-class-name: com.mysql.cj.jdbc.Driver # 데이터베이스 드라이버 클래스 이름
      jpa:
        hibernate:
          ddl-auto: update # 데이터베이스 테이블 자동 생성, 운영 단계에서는 none으로 설정
        show-sql: true # 데이터베이스 쿼리 로그 출력
        properties:
          hibernate:
            format_sql: true # 데이터베이스 쿼리 로그 포맷팅
            dialect: org.hibernate.dialect.MySQL8Dialect # 데이터베이스 방언
      security:
        oauth2:
          client:
            registration: # 클라이언트 앱이 Oauth 서버에 등록한 정보 / 우리 앱이 등록한 정보
              # 구글 클라이언트 정보
              google:
                client-id: ${GOOGLE_CLIENT_ID} # 구글 클라이언트 ID
                client-secret: ${GOOGLE_CLIENT_SECRET} # 구글 클라이언트 비밀번호
                scope:
                  - email # 구글 클라이언트 범위
                  - profile # 구글 클라이언트 프로필
              
              # 카카오 클라이언트 정보
              kakao:
                client-id: ${KAKAO_CLIENT_ID} # 발급 받은 Client ID
                # client-secret: # 발급 받은 Client Secret -> 보안 강화 전엔 사용하지 않아도 됨
                client-authentication-method: client_secret_post # 클라이언트 인증 방법
                authorization-grant-type: authorization_code # 인증 유형
                scope:
                  - profile_nickname
                  - profile_image
                  # - account_email, 아직 인가받지 못함
                redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
                client-name: Kakao
            
            provider: # 프로바이더 정보, Oauth 서버에서 제공하는 정보
              # 구글 프로바이더 정보
              google:
                authorization-uri: https://accounts.google.com/o/oauth2/auth # 구글 인증 요청 URL
                token-uri: https://oauth2.googleapis.com/token # 구글 토큰 요청 URL
                user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo # 구글 사용자 정보 요청 URL
                user-name-attribute: sub # Google oauth2에서 고유하게 보장되는 ID

              # 카카오 프로바이더 정보
              kakao:
                authorization-uri: https://kauth.kakao.com/oauth/authorize # 카카오 인증 요청 URL
                token-uri: https://kauth.kakao.com/oauth/token # 카카오 토큰 요청 URL
                user-info-uri: https://kapi.kakao.com/v2/user/me # 카카오 사용자 정보 요청 URL
                user-info-authentication-method: header # 카카오 사용자 정보 인증 방법
                user-name-attribute: id # Kakao 사용자 고유 ID
